---
abstract: Because we are not God, we cannot know the full nature of God, or even for
  certainty whether God exists at all. As a result, we cannot know any purpose, including
  ultimate purpose, each of our lives may have. Because we cannot know the full nature
  of God, should He exist, nor any purpose our lives may have in His sight, we lack
  the authority to compel the beliefs of others, lest we lead them into ultimate error.
author: James Lindsay
date: '2023-11-10'
link: https://newdiscourses.com/2023/11/basis-of-classical-liberalism/
media_url: ''
title: The Basis of Classical Liberalism
---
<https://newdiscourses.com/2023/11/basis-of-classical-liberalism/>

- We are not God, and cannot assume His authority or fully understand His nature or existence.
- Our lack of divine authority means we cannot compel others' beliefs or claim authority over them.
- All humans are politically equal, as no one has intrinsic authority over another without mutual consent.
- Authority over others must be earned, provisional, temporary, and voluntarily given and accepted.
- Governments should not compel beliefs, speech, or actions, as they lack divine authority.
- A just government operates with the consent of the governed, securing inalienable rights and facilitating peaceful dispute resolution.
- Just governments are democratic and republican, ensuring fair representation and protecting minority rights.
- Governments must secure rights to speech, press, protest, and petition, and operate within a system of checks and balances.
- Individual belief and conscience are inviolate; governments must protect privacy and cannot violate the sanctity of the human mind.
- Social and political authority among individuals must be based on consent and demonstrated competence.
- Beliefs and propositions must earn authority through validation and competition of ideas, not by compulsion.
- Property rights are inalienable, supporting the right to engage in commerce under free enterprise principles.
- The article outlines principles of classical liberalism, emphasizing political equality, inalienable rights, and the limitations of human and governmental authority.