---
abstract: It isn’t possible to discuss Intersectionality without starting with Kimberlé
  Crenshaw, who named it. Like with most Woke Marxist ideas, though, Intersectionality
  is recycled and repackaged, more than once. Crenshaw is therefore the wrong person
  to discuss to talk about the issue, but she’s a starting place.
author: James Lindsay
date: '2023-05-02'
link: https://newdiscourses.com/2023/05/intersectionality-is-american-maoism/
media_url: ''
title: Intersectionality Is American Maoism
---
<https://newdiscourses.com/2023/05/intersectionality-is-american-maoism/>

- Kimberlé Crenshaw coined the term "Intersectionality" in 1989, describing it as the overlapping of systemic oppressions, like racism and sexism, experienced by individuals with multiple marginalized identities.
- Crenshaw's concept suggests that systemic oppression is not additive but multiplicative, creating unique challenges for people at the intersection of multiple marginalized groups.
- Intersectionality aims to understand and address the interconnected nature of social categorizations and their ability to create overlapping systems of discrimination or disadvantage.
- The doctrine of Intersectionality is not just theoretical but also calls for practice through activism aimed at achieving equity by raising critical consciousness and linking various forms of oppression.
- Critics argue that Intersectionality, as part of broader Marxist ideologies, overlooks individuality, promoting a divisive and collectivist approach that prioritizes group identity over personhood.
- The origins of Intersectionality are traced back to the Black Feminism movement and the Combahee River Collective, which emphasized the interconnectedness of all forms of oppression.
- The article suggests that Intersectionality and its focus on identity politics have roots in Marxist thought, particularly influenced by Herbert Marcuse and Mao Zedong's strategies for societal transformation through identity-based radicalization.
- The piece warns of the potential dangers of adopting Intersectionality uncritically, suggesting it could lead to societal division and the eventual discarding of its proponents once their utility to the movement ends.
- The author advises young people involved in the Woke movement to reconsider their participation, emphasizing the importance of individual liberty and cautioning against the seductive but ultimately destructive promises of liberation movements.