---
abstract: Queer Theory, which nearly all of the gender and sexuality education in
  America is ultimately based upon, has nothing to do with "LGBT" education.
author: James Lindsay
date: '2023-08-23'
link: https://newdiscourses.com/2023/08/queer-education-is-child-abuse/
media_url: ''
title: Queer Education is Child Abuse
---
<https://newdiscourses.com/2023/08/queer-education-is-child-abuse/>

- Queer Theory is foundational to gender and sexuality education in America but is distinct from LGBT education.
- Emily Drabinski, president of the American Library Association, differentiates between lesbian and gay studies and Queer Theory, emphasizing the latter's focus on the societal roles and activism of queer identities.
- Queer Theory, as defined by David Halperin, is oppositional and not tied to any specific identity or essence, focusing instead on challenging norms.
- The application of Queer Theory in education aims to disrupt traditional norms and encourage activism, which is seen as inappropriate by some for educational settings.
- Drag Queen Story Hours (DQSH) and similar educational approaches are criticized for introducing children to "alternate modes of kinship" and "living queerly," which some view as a form of grooming.
- Queer Theory's goals in education include challenging the concept of childhood innocence and promoting "queer curiosity," which is controversial and seen by some as harmful.
- The article argues against the inclusion of Queer Theory-based materials in education, labeling it as damaging and inappropriate for children.