---
abstract: A great deal of subversion has already taken place in both low courts and
  high, though we’re also seeing a wakening judiciary quickly starting to realize
  the problem and its underlying nature. This rousing of the judiciary is patently
  visible in the Dobbs decision that overturned Roe v. Wade, especially in light of
  Justice Clarence Thomas’s remarks about misapplications of substantive due process
  in that and other decisions.
author: James Lindsay
date: '2023-08-30'
link: https://newdiscourses.com/2023/08/rousing-the-american-judiciary/
media_url: ''
title: Rousing the American Judiciary
---
<https://newdiscourses.com/2023/08/rousing-the-american-judiciary/>

- The article argues that "Woke Marxism" is undermining law by perverting it to advance its own ends, a process that has been ongoing since the Critical Legal Theory movement in the 1970s and 1980s, through Critical Race Theory and legal and judicial activism.
- It suggests that the judiciary is beginning to recognize this subversion, as evidenced by decisions like the Dobbs decision overturning Roe v. Wade and the Supreme Court's stance on racial discrimination in college admissions, challenging the logic behind "Diversity, Equity, and Inclusion."
- The article claims that law has been subverted through decades of intentional activism, exploiting judges' reliance on domain-specific information and expert testimony, which has been hijacked by activists.
- It traces the ideological roots of this subversion to Western Marxism, particularly Antonio Gramsci's concept of "cultural hegemony" and the strategy of infiltrating cultural institutions to promote socialism and Marxism.
- The article highlights the capture of the higher education system and professional organizations by Critical Marxist thought, leading to a professional class of activists influencing the judiciary with distorted expert opinions and studies.
- It points out the manipulation of language by activists, using terms like "diversity," "inclusion," "hate," "harm," and "trauma" with specialized meanings to further their agenda.
- The article calls for the judiciary to be aware of the capture of expertise and language, advocating for prudence and discernment in rendering judgments without necessarily becoming experts in "Woke" language or ideological subversion.
- It emphasizes the importance of addressing the manipulation of language, as it can change the entire meaning of laws or rulings without altering the wording, citing the potential for Marxist manipulation of property rights as an example.
- The article concludes with a call to action to stop the Gramscian infiltration and subversion of law by making the judiciary aware of the tainted nature of expertise, expert testimony, and language due to decades of Critical activism.