---
abstract: It has become relatively obvious that what goes by the term “Woke” refers
  to having been initiated into a cult.
author: James Lindsay
date: '2023-03-22'
link: https://newdiscourses.com/2023/03/wokeness-and-the-structure-of-cults/
media_url: ''
title: Wokeness and the Structure of Cults
---
<https://newdiscourses.com/2023/03/wokeness-and-the-structure-of-cults/>

- The article argues that the term "Woke" refers to initiation into a cult-like structure without many realizing it.
- It outlines a general structure of cults, consisting of three internal layers (initiates, adepts, and leaders/disciples) and two external categories (potential recruits and enemies).
- Initiates, or the "Outer School," have little knowledge of cult doctrine but are morally and socially aligned with it, learning through social reinforcement.
- Adepts, or the "Inner School," understand and teach the doctrine in digestible ways, having committed to the cult morally and psychologically first.
- The "Inner Circle" consists of leaders chosen for loyalty, possibly including those seeking power without true belief in the doctrine.
- Cult dynamics involve a cycle of abuse and victimization, with each layer exploiting the one below.
- The article compares these dynamics to Mao Zedong's socialist cult, emphasizing a process of "unity – criticism – unity."
- Outside the cult, there are potential recruits ("masses") and adversaries ("enemies"), with growth depending on recruiting the uninitiated and suppressing enemies.
- The article claims most "Woke" individuals are initiates, adopting Woke ideology and identity before deeply studying its theory, with few reaching the leadership circle.
- It suggests that understanding the cult-like structure and theory behind "Woke" is crucial for addressing and potentially deprogramming its adherents.