---
abstract: It has become relatively obvious that what goes by the term “Woke” refers
  to having been initiated into a cult.
author: James Lindsay
date: '2023-03-29'
link: https://newdiscourses.com/2023/03/workings-of-the-woke-cult/
media_url: ''
title: The Workings of the Woke Cult
---
<https://newdiscourses.com/2023/03/workings-of-the-woke-cult/>

- The article discusses the structure of cults, focusing on the "Woke Marxist cult," which is described as having three layers: an Outer School of low-information initiates, an Inner School of informed adepts, and Inner Circles of leaders and directors.
- Wokeness is characterized as decentralized and informal, likened to a "mind virus" rather than a traditional cult, with its doctrine spread through various means including education, media, and social interactions.
- The process of cult induction involves cycles of alienation and affirmation, leading to a deepening commitment through criticism and self-critique, aimed at reshaping the individual's identity in line with the cult's ideology.
- The article outlines the progression from the Outer School to the Inner School through increased commitment and study, emphasizing the role of praxis (applying doctrine in practice) and the importance of theory as the cult's doctrine.
- It is suggested that the most committed members may progress to the Inner Circle, where they learn the cult's true purposes and become part of its leadership, directing activities for their own benefit.
- The article argues that understanding Woke as a cult structured similarly to Maoist Communism is crucial for comprehending its influence and formulating responses to it, highlighting the importance of recognizing the ideological and financial mechanisms that sustain it.