---
abstract: There is much that should be said about the ways in which the dominant Social
  Justice ideology has negative impacts upon the university, free expression, academic
  freedom and, especially, the sciences.
author: James Lindsay
date: '2019-12-25'
link: https://newdiscourses.com/2019/12/academics-cowards-grievance-studies-academic-pursuit/
media_url: ''
title: Are Academics Cowards? The Grip of Grievance Studies and the Sunk Costs of
  Academic Pursuit - New Discourses
---
<https://newdiscourses.com/2019/12/academics-cowards-grievance-studies-academic-pursuit/>

- Social Justice ideology negatively impacts universities, free expression, academic freedom, and the sciences by prioritizing predetermined conclusions over scientific inquiry.
- Scientists are confident in their methodology, believing it immune to ideological influence, but may underestimate the susceptibility of science to dominant orthodoxies.
- Social Justice critics argue science is biased towards white, Western male perspectives, necessitating inclusivity, but this contradicts the universality and skepticism fundamental to scientific method.
- There's concern that ideologically motivated individuals could influence scientific agendas, undermining the objectivity and core values of scientific inquiry.
- Many scientists recognize the potential for Social Justice to corrupt science but remain silent due to fear of repercussions, such as job loss, funding denial, and professional ostracization.
- The academic job market's competitiveness and the specialized nature of PhD qualifications limit career options, making academics reluctant to risk their positions by speaking out against prevailing ideologies.
- Achieving change requires collective action and open communication among academics to counteract the institutionalization of Social Justice orthodoxy.
- Academics are encouraged to engage in safe forms of resistance, such as anonymous posting or finding like-minded colleagues, to challenge the overreach of educational reformers and Social Justice advocates.