---
abstract: Jordan Peterson’s star appeal isn’t curious at all to anyone who understands
  the inner mechanics of religious movements.
author: James Lindsay
date: '2019-12-27'
link: https://newdiscourses.com/2019/12/guru-appeal-jordan-peterson-post-everything-world/
media_url: ''
title: The Guru Appeal of Jordan Peterson in Our Post-Everything World
---
<https://newdiscourses.com/2019/12/guru-appeal-jordan-peterson-post-everything-world/>

- Douglas Murray wrote an adulatory article on Jordan Peterson's appeal to young Brits, exploring why they are drawn to his talks on morality.
- Peterson, a University of Toronto professor, is seen as a mix of philosopher, life-coach, educator, and guru, attracting a passionate following that rivals organized religions.
- Murray suggests Peterson's appeal lies in his ability to fill a moral and spiritual vacuum left by the decline of traditional Christian values and the rise of moral relativism.
- Peterson's fans are known for their fervent defense of him on social media, often reacting poorly to criticism.
- Murray describes Peterson as a counter-cultural hero who speaks to young people, especially men, who feel marginalized by modern societal narratives.
- Peterson's message includes criticism of social justice movements and offers a "middle way" that avoids the extremes of social justice leftism and alt-right ideologies.
- He emphasizes personal responsibility, urging his followers to focus on improving themselves before criticizing the world.
- Peterson's approach is likened to leading a nascent religious movement, offering principles and certainties that resonate with his audience.
- His use of religious and mythological symbolism, combined with a pragmatic approach to truth, adds depth to his message, making it more appealing and relatable.
- Peterson's popularity is attributed to his ability to articulate a vision of masculinity and societal structure that appeals to young men feeling disenfranchised by current cultural trends.
- The article concludes that Peterson's guru-like appeal stems from his ability to provide a sense of identity, purpose, and belonging to a generation of "lost boys" in a post-everything world.