---
abstract: “Freedom is the freedom to say that 2+2=4. If that is granted, all else
  follows” -George Orwell, Nineteen Eighty-four
author: James Lindsay
date: '2020-08-03'
link: https://newdiscourses.com/2020/08/2-plus-2-never-equals-5/
media_url: ''
title: 2+2 Never Equals 5
---
<https://newdiscourses.com/2020/08/2-plus-2-never-equals-5/>

- The article discusses the bizarre need to defend the basic truth that 2+2=4 against ideological attacks suggesting otherwise.
- It highlights how Critical Social Justice activists argue against objective truths, like 2+2=4, to advance their agenda.
- The author explains various tactics used by activists to argue that 2+2 can equal 5, including redefining terms and playing word games.
- The piece argues that postmodernism, especially within Critical Social Justice, aims to destabilize meaning to gain power and control over what is considered true.
- The author warns against becoming an "accomplice" to this ideology, which seeks to undermine reason and the fundamental logic of civilization.
- The article concludes by emphasizing the importance of defending objective truths for the sake of freedom and civilization's stability.