---
abstract: The real trouble with activist violence has less to do with efficacy than
  with democracy.
author: New Discourses
date: '2020-09-06'
link: https://newdiscourses.com/2020/09/activist-violence-context/
media_url: ''
title: Activist Violence in Context
---
<https://newdiscourses.com/2020/09/activist-violence-context/>

- Activists sometimes use force not to win over people but to coerce them, which can be seen as counterproductive by critics.
- Examples of such tactics include intimidation by animal rights activists and physical harassment of Google employees, which have been defended as effective in achieving goals.
- The use of violence by activists is compared to political actors testing limits, with more transgressions being indulged leading to bolder actions.
- Sidney Hook argued that in a democracy, citizens should obey laws unless actively working to change them through due process, to avoid tyranny and anarchy.
- Hook criticized the view that individual conscience can override laws, emphasizing the need for moral justification and intelligence in moral decisions.
- The article suggests that in a liberal democracy, grievance does not justify breaking the law or resorting to violence to achieve demands.
- It criticizes the double standard where violence by certain groups is condemned while similar actions by others are excused or justified.
- The conclusion is that a free society requires peace and the ability to engage with political rivals without resorting to violence, and those who undermine this are not heroes but "pop-up tyrants."