---
abstract: Because it wants to continue taking money directly, Black Lives Matter UK
  has become an official organization and, in the process, renamed itself “Black Liberation
  Movement UK.” This obviously allows it to retain its BLM UK branding without changing
  anything about its politics.
author: James Lindsay
date: '2020-12-08'
link: https://newdiscourses.com/2020/12/blm-based-on-conspiracy-theory/
media_url: ''
title: Is BLM Based On a Conspiracy Theory?
---
<https://newdiscourses.com/2020/12/blm-based-on-conspiracy-theory/>

- Black Lives Matter UK has officially become an organization and renamed itself “Black Liberation Movement UK” to continue taking direct donations without altering its political stance.
- Elliott Cooper, who registered the entity, emphasized that their commitment and politics remain unchanged, maintaining a global dialogue with other Black Lives Matter groups.
- The concept of "black liberation" is rooted in neo-Marxist ideology, drawing from Marx's idea of emancipation from capitalism and systemic oppression, aiming for a society free from the liberal order and Enlightenment rationalism.
- Herbert Marcuse, a neo-Marxist, argued that liberation requires the suppression of civil rights for those in power to enable the oppressed to exercise their rights, suggesting a radical overhaul of society towards socialism.
- Angela Davis, influenced by Marcuse, joined the Black Liberation Army, focusing on black liberation within the BLM context, which implies a rejection of all forms of servitude and domination, starting from individual consciousness.
- The Black Liberation Army's perspective on liberation criticizes the law and democracy in North America as tools of capitalist exploitation and control, advocating for the liberation of black people from systemic oppression.
- Black liberationism seeks to free black individuals from all forms of systemic oppression, challenging concepts like equal opportunity, justice, and social equality as mechanisms of capitalist and liberal oppression.
- The renaming of BLM UK to Black Liberation Movement UK may help clarify the movement's foundational beliefs and goals, rooted in a neo-Marxist critique of capitalist societies, to the public.