---
abstract: The Woke use a very particular, very narrow definition of “racism” that
  has a very expansive application because it is believed to be “systemic” and thus
  applicable to and a part of everything.
author: James Lindsay
date: '2020-07-18'
link: https://newdiscourses.com/2020/07/can-white-people-understand-racism/
media_url: ''
title: Can White People Understand "Racism"?
---
<https://newdiscourses.com/2020/07/can-white-people-understand-racism/>

- The article discusses the challenge of addressing accusations of racism within the context of "Woke ideology," which defines racism as "prejudice plus power," a concept believed to be systemic and pervasive, particularly in Western societies.
- It critiques the notion that white people inherently cannot understand racism due to their position within a historically dominant racial group, arguing that this perspective oversimplifies and misrepresents the complexity of racism and historical power dynamics.
- The author examines historical examples, such as the enslavement of Slavs in the 9th century and racial dynamics in India, to challenge the Woke ideology's narrow definition of racism as exclusively a product of white, Western power structures.
- The article argues that the Woke definition of racism fails to account for the full range of human experiences with prejudice and discrimination, including those where white people are victims.
- It suggests that progress in combating racism has come from moving beyond systemic definitions to focus on individual beliefs and actions, advocating for a more inclusive and nuanced understanding of racism.
- The author concludes that while fully convincing those deeply invested in Woke ideology may be difficult, a broader, more historically and culturally informed perspective on racism can appeal to a wider audience and foster more effective dialogue and understanding.