---
abstract: People who observe that Marxism is somehow tied into all of this Woke stuff,
  then, are certainly not wrong, but it just as certainly isn’t Marxism.
author: James Lindsay
date: '2020-07-28'
link: https://newdiscourses.com/2020/07/complex-relationship-between-marxism-wokeness/
media_url: ''
title: The Complex Relationship between Marxism and Wokeness
---
<https://newdiscourses.com/2020/07/complex-relationship-between-marxism-wokeness/>

- The book "Cynical Theories" by Helen Pluckrose and the author focuses on the postmodern elements of Critical Social Justice (CSJ) scholarship and activism.
- There is confusion about the relationship between Marxism and CSJ, as postmodernism is critical of Marxism, yet CSJ seems to incorporate Marxist elements.
- CSJ is described as a fusion of neo-Marxism (or Cultural Marxism from the Frankfurt School) and postmodernism, aiming to achieve social justice through radical identity politics.
- Neo-Marxism retains Marxism's ethos and ambition but shifts focus from economics to culture and ideology as the primary fields of conflict.
- Postmodernism, seen as post-Marxism, abandons hope in Marxism and focuses on the power dynamics in society, especially through language and discourses.
- The book argues that CSJ is not strictly Marxist but is influenced by Marxian conflict theory applied to identity groups and uses postmodern techniques for deconstructing oppressive power structures.
- Marxism focuses on economic class struggle, while CSJ emphasizes identity politics, often overlooking economic factors in favor of racial or cultural analyses.
- CSJ's approach can sometimes resemble Marxism when it comes to practical demands, such as equitable and diverse hiring, but it fundamentally differs by prioritizing identity over class.
- The relationship between Marxism, neo-Marxism, postmodernism, and CSJ is complex, with CSJ being a descendant that evolves against both reality and liberal societies.