---
abstract: For this “virus,” we need a liberal immune response (critical thinking)
  that minimizes its influence while keeping the liberal body politic intact and healthy.
author: James Lindsay
date: '2020-03-17'
link: https://newdiscourses.com/2020/03/critical-theories-virus-liberal-body-politic/
media_url: ''
title: 'Critical Theories: A Virus on a Liberal Body Politic'
---
<https://newdiscourses.com/2020/03/critical-theories-virus-liberal-body-politic/>

- The Covid-19 pandemic has heightened public interest in virology, revealing how viruses exploit cells to replicate.
- In 2016, feminist scholars Fahs and Karger published a paper likening women's studies to a virus, suggesting it should disrupt traditional fields and alter their purposes, drawing parallels between the spread of viruses and the impact of women's studies.
- The paper argues for women's studies to embrace its role as a transformative and disruptive force within academia and beyond, suggesting this approach could lead to positive changes.
- The article critiques critical theories, particularly Critical Social Justice, for acting like a virus within liberal societies, undermining norms, values, and patterns that make these societies adaptive and effective.
- Critical theories are distinguished from critical thinking, with the former seen as a perversion of the latter, aiming to subvert and replace liberal, rationalist, and empirical approaches with neo-Marxist ideology.
- The metaphor of a virus is used to describe how critical theories infiltrate and transform liberal systems, spreading their influence across various fields.
- The article calls for a liberal response to counteract the influence of critical theories, emphasizing the importance of understanding and resisting these ideas to preserve the liberal order and promote genuine progress.