---
abstract: Fast jeder hat einen Woke Belastungsgrenze. Ein Punkt von Peak Woke. Oder
  zumindest sollten sie es tun.
author: James Lindsay
date: '2020-07-08'
link: https://newdiscourses.com/2020/07/die-woke-belastungsgrenze/
media_url: ''
title: Die Woke Belastungsgrenze
---
<https://newdiscourses.com/2020/07/die-woke-belastungsgrenze/>

- Jeder sollte eine "Woke Belastungsgrenze" haben, einen Punkt, an dem erkenntlich wird, dass eine Bewegung zu weit gegangen ist.
- Extreme Aspekte der Woke Ideologie könnten potenziell totalitäre Züge annehmen, was besorgniserregend ist.
- Es ist wichtig, sich und andere zu ermutigen, nicht-verhandelbare Grenzen zu definieren, um zu erkennen, wann diese überschritten werden.
- Die Frage, was jemanden dazu bringen würde, zu entscheiden, dass die Woke-Bewegung zu weit gegangen ist, soll zum Nachdenken anregen.
- Diskussionen über persönliche Belastungsgrenzen können schwierig sein und auf Widerstand stoßen, sind aber notwendig.
- Beispiele für überschrittene Grenzen umfassen ungerechtfertigte Anschuldigungen, Angriffe auf die Wissenschaft, echten Rassismus, und die Verteidigung von Gewalt.
- Es ist wichtig, spezifische Fragen zu stellen, um Menschen dazu zu bringen, über ihre Grenzen nachzudenken, wie z.B. welche Statuen fallen müssen oder wer gecancelt werden muss.
- Selbst wenn die Diskussion nicht erfolgreich ist, ist es wichtig, dass die Menschen über ihre Grenzen und Prinzipien nachdenken, bevor sie diese unbewusst überschreiten.
- Das Ziel ist nicht unbedingt, Meinungen zu ändern, sondern Menschen dazu zu bringen, sich mit ihren eigenen Prinzipien auseinanderzusetzen und zu überlegen, was für sie zu weit geht.