---
abstract: We're being lied to, and it's been costing us a fortune, both economically
  and socially.
author: James Lindsay
date: '2020-06-28'
link: https://newdiscourses.com/2020/06/diversity-delusion/
media_url: ''
title: The Diversity Delusion
---
<https://newdiscourses.com/2020/06/diversity-delusion/>

- The article criticizes the Diversity, Inclusion, and Equity (DIE) industry, claiming it sells ineffective solutions that harm workplaces and society, despite its annual revenue in the tens of billions.
- It argues that DIE consulting exploits good intentions and manipulates language to advance a political agenda rooted in Critical Theory and Critical Social Justice, leading to less effective and more divided workplaces.
- The article contends that the DIE industry's definitions of "Diversity," "Inclusion," and "Equity" are based on Critical Theory, focusing on identity politics and systemic power dynamics rather than improving workplace culture or societal fairness.
- "Diversity" is criticized for promoting a narrow view that values only certain political perspectives within identity groups, leading to hiring based on ideology rather than genuine diversity.
- "Inclusion" is described as limiting speech and behavior to avoid offending those who subscribe to Critical Theory, effectively excluding dissenting views and creating a conformist environment.
- "Equity" is differentiated from equality, with the former aiming for equal outcomes through social engineering and potentially endless discrimination against perceived dominant groups.
- The article concludes that the DIE industry, as influenced by Critical Theory, misrepresents its goals and methods, ultimately failing to address real issues of inequality and instead fostering division and inefficiency.