---
abstract: Many of you have noticed that more people than ever are presenting the stock
  Critical Race Theory ideas.
author: James Lindsay
date: '2020-06-01'
link: https://newdiscourses.com/2020/06/do-better-than-critical-race-theory/
media_url: ''
title: Do Better than Critical Race Theory
---
<https://newdiscourses.com/2020/06/do-better-than-critical-race-theory/>

- Critical Race Theory (CRT) has become more mainstream, especially following the Black Lives Matter protests.
- The rapid mainstreaming of CRT is seen as problematic by some, as it is believed to lead to more harm than healing.
- There is an opportunity to educate people about CRT, highlighting its incorrect diagnoses and harmful prescriptions for societal issues.
- CRT points to real problems but is criticized for its analysis and solutions, promoting a divisive and cynical view of the world.
- CRT is based on several assumptions, including the ordinariness of racism, interest convergence, criticism of liberalism, and a rejection of traditional evidence and reality in favor of storytelling and lived experiences.
- CRT is seen as pessimistic, denying the possibility of progress and promoting a divisive identity-first approach.
- The article argues for rejecting CRT not for its observations but for its analysis and prescriptions, advocating for a return to liberal approaches to address societal issues.
- It emphasizes the need to listen and understand real problems but rejects CRT's divisive and harmful methods, calling for working together and finding common ground.