---
abstract: My journey into the centre of a dark political world, and how I escaped.
author: New Discourses
date: '2020-10-27'
link: https://newdiscourses.com/2020/10/everything-problematic/
media_url: ''
title: '"Everything Is Problematic"'
---
<https://newdiscourses.com/2020/10/everything-problematic/>

- Yarrow Eady, a queer activist since 17, faced anti-gay hatred in a conservative town but was motivated to make a change.
- Influenced by Judith Butler, Eady embraced third-wave feminism and queer theory, leading to activism at McGill University.
- Eady's activism expanded to include a variety of queer, feminist, and radical leftist groups, participating in protests and radical actions.
- Over time, Eady's political views evolved, moving away from radicalism towards a more nuanced understanding of anti-oppressive politics.
- Eady critiques a specific brand of radical leftist, anti-oppressive politics at McGill for its dogmatism, groupthink, crusader mentality, and anti-intellectualism.
- The article discusses the dangers of sacred beliefs, the division between ingroups and outgroups, and the rejection of theoretical knowledge.
- Eady argues against the infallibility of oppressed groups in understanding oppression and advocates for a more reasoned, individual approach to activism.
- The article concludes with advice for activists: embrace humility, treat people as individuals, be diplomatic, and take a systems approach to political issues.
- Eady reflects on past activism with both nostalgia and regret, aiming to share lessons learned and encourage constructive, thoughtful activism.