---
abstract: Today’s social justice warriors in academic fields such as gender studies
  share unfortunate commonalities with Adolf Hitler's 'struggle.'
author: New Discourses
date: '2020-04-20'
link: https://newdiscourses.com/2020/04/grievance-studies-affair-academias-social-justice-warriors/
media_url: ''
title: What The 'Grievance Studies Affair' Says About Academia's Social Justice Warriors
---
<https://newdiscourses.com/2020/04/grievance-studies-affair-academias-social-justice-warriors/>

- Adolf Hitler, known for his notorious role in history, was posthumously published in a peer-reviewed scholarly journal due to the "Grievance Studies affair."
- The affair involved James A. Lindsay, Helen Pluckrose, and Peter Boghossian publishing fake papers in social justice-oriented journals, including a rebranded segment of Hitler's "Mein Kampf" to critique the academic field.
- The authors argue that social justice warriors (SJWs) in academia share similarities with Hitler, focusing on grievances and adopting a Manichean worldview that divides people into oppressor and oppressed groups based on social identity.
- The article criticizes the current state of social justice discourse in academia for opposing free speech, scientific inquiry, and individual merit, drawing parallels to totalitarianism.
- Examples of extreme social justice proposals include reparations-based teaching methods that demean white males and the rejection of satire that critiques social justice.
- The article also highlights the negative impact of SJW ideologies on academia, including speaker dis-invitations, censorship, and the limiting of employment prospects for politically incorrect professors.
- It calls for congressional hearings and state legislature actions to address these issues and emphasizes the need for intellectual diversity and free speech across the political spectrum.
- The piece concludes by urging both academics and the broader public to reflect on their actions and ideologies, advocating for a move towards intellectual diversity and away from divisive identity politics.