---
abstract: Helen Pluckrose develops the definition of "Social Justice" as it is used
  in the academic literature in this tradition, explains its connections to identity
  politics and the political correctness movement, and then shows the relevance of
  the original postmodernists to this Theory in some detail.
author: New Discourses
date: '2020-06-22'
link: https://newdiscourses.com/2020/06/helen-pluckrose-evolution-postmodern-thought/
media_url: ''
title: 'Helen Pluckrose: The Evolution of Postmodern Thought'
---
<https://newdiscourses.com/2020/06/helen-pluckrose-evolution-postmodern-thought/>

- Conference held in London at the Gladstone Library in the National Liberal Club focused on "Speaking Truth to Social Justice."
- Helen Pluckrose was among the speakers, aiming to define "Social Justice" as understood by its most vocal proponents today, linking it to radical identity politics, political correctness, and postmodern epistemology.
- Pluckrose outlined the academic origins of Social Justice, its ties to identity politics and political correctness, and its roots in postmodernist theory.
- She detailed the evolution of these ideas from academic theory to activism and mainstream acceptance, highlighting the work of theorists like Peggy McIntosh, Barbara Applebaum, and Robin DiAngelo.
- Pluckrose argued that the latest generation of theorists simplified complex ideas, making them more accessible and leading to their widespread adoption.
- The talk aimed to provide an intellectual history of Critical Social Justice.

The presentation is available on Soundcloud, Apple Podcasts, Google Play, Spotify, and Stitcher.