---
abstract: Even the Constitution offers us uncomfortably little protection against
  Woke totalitarianism as the Woke gain cultural hegemony and, as a result, control
  over ever more levers of power.
author: James Lindsay
date: '2020-11-23'
link: https://newdiscourses.com/2020/11/how-wokeness-undermines-constitution/
media_url: ''
title: How Wokeness Undermines The Constitution
---
<https://newdiscourses.com/2020/11/how-wokeness-undermines-constitution/>

- The article discusses the impact of Critical Theory, including Postcolonialism and Critical Race Theory, on public narratives about stolen land and labor.
- It argues that these narratives could undermine the protections of the Fourth Amendment by reinterpreting property rights through the lens of "stolen property."
- The article suggests that Woke ideology could subvert not only the Fourth but also other Amendments and principles of the U.S. Constitution without changing their wording, by altering their interpretation and application.
- It highlights concerns about the potential for Woke ideology to reinterpret the Fifth Amendment's protections against self-incrimination and due process, the Thirteenth Amendment on involuntary servitude, the Eighth Amendment's stance on cruel and unusual punishment, the Sixth Amendment's right to an impartial jury, the Second Amendment's clause on a well-regulated militia, and the First Amendment's speech protections.
- The article also touches on the Nineteenth Amendment, suggesting it is criticized within Woke circles for not adequately supporting black women.
- It concludes that Woke ideology poses a threat to the Constitution by waging a war on interpretation, meaning, and context, and calls for resistance against this perceived empowerment of Woke ideology.