---
abstract: If you own a business or run an organization, there’s a fairly good chance
  that you might be concerned about how you can resist the social pressure of the
  “Woke” mob, should it come yelling (or tweeting).
author: James Lindsay
date: '2020-08-07'
link: https://newdiscourses.com/2020/08/how-your-organization-can-resist-woke-social-pressure/
media_url: ''
title: How Your Organization Can Resist Woke Social Pressure
---
<https://newdiscourses.com/2020/08/how-your-organization-can-resist-woke-social-pressure/>

- Businesses and organizations are increasingly facing social pressure from "Woke" activism, including demands for structural changes, diversity training, and other actions.
- Avoiding confrontation with such activism is challenging due to the pervasive nature of social media and the current social climate.
- Succumbing to these pressures often leads to further demands, as concessions are seen as weaknesses.
- Internal unity and a strong organizational culture are crucial for resisting external pressures and maintaining operational integrity.
- Examples include Trader Joe's resisting demands to change product branding and Red Bull firing senior management to avoid internal division.
- Introducing divisive political activism into the workplace can undermine organizational culture and distract from operational goals.
- Leadership should focus on cultivating a team-oriented, anti-fragile mindset and differentiate between liberal and critical approaches to issues like anti-racism and diversity.
- Critical diversity, anti-racism, or bias training can create internal divisions and are not recommended.
- The internet and certain educational trends have contributed to the rise of online outrage mobs, making it important for organizations to maintain a strong internal culture to withstand such pressures.