---
abstract: You are a soldier in a war being waged right now.
author: New Discourses
date: '2020-07-31'
link: https://newdiscourses.com/2020/07/hurtling-toward-totalitarianism-call-action-defense-all-we-hold-dear/
media_url: ''
title: 'Hurtling Toward Totalitarianism: A Call To Action In Defense Of All We Hold
  Dear'
---
<https://newdiscourses.com/2020/07/hurtling-toward-totalitarianism-call-action-defense-all-we-hold-dear/>

- The article posits that society is currently engaged in a significant ideological battle, with the author urging readers to recognize their role in it.
- The enemy is identified as "The Woke," described as a movement that has infiltrated various institutions and is challenging traditional understandings of objective reality.
- The author argues that this movement threatens everything from personal beliefs to societal structures by promoting subjective truths over objective facts.
- Critical Theory is criticized for distorting issues like race and sexuality, aiming to redefine truth and gain control over societal narratives.
- The article warns of the dangers of not confronting this ideology, suggesting it could lead to societal division, loss of democratic values, and even civil war.
- The author calls for a commitment to reason, encouraging readers to stand firm on objective truths and engage in critical thinking to counter poor arguments and emotional manipulations.
- The piece concludes with a call to action, urging readers to actively participate in defending reason to prevent a slide into totalitarianism.