---
abstract: The nature of book-burnings and iconoclasm lends itself to ideology.
author: New Discourses
date: '2020-06-19'
link: https://newdiscourses.com/2020/06/iconoclasm-prelude-woke-horrors/
media_url: ''
title: Iconoclasm as a Prelude to Woke Horrors?
---
<https://newdiscourses.com/2020/06/iconoclasm-prelude-woke-horrors/>

- The article begins with a quote from Ray Bradbury's _Fahrenheit 451_, highlighting the destructive pleasure of burning books.
- It references a famous quote by Heinrich Heine about the progression from burning books to burning people, inscribed on the Empty Library Memorial in Berlin, which commemorates the Nazi book burnings.
- The quote's origin is from Heine's 1823 work _Almansor_, set during the reconquista of Spain, predicting violence that foreshadowed the Spanish Inquisition.
- The article discusses the historical context of book burnings and iconoclasm, noting their role in escalating violence, from the Spanish Inquisition and French Revolution to Nazism.
- It draws parallels between past instances of iconoclasm and the modern "woke" movement, suggesting a pattern of reducing complex figures to a single negative aspect, leading to the destruction of statues and monuments.
- The article argues that such actions dehumanize the subjects represented, potentially leading to further violence and division.
- It advocates for a respectful and deliberate approach to removing statues, akin to a formal funeral, after public deliberation and judgment, emphasizing the importance of preserving humanity.
- The article concludes by warning against the dangers of dehumanization through the destruction of books and statues, suggesting it could lead to political assassinations, civil unrest, or even revolution.