---
abstract: Sociology is a complicated topic. As we said when we went public with the
  Grievance Studies Affair, and as we have come to understand even better since, it's
  best to think of grievance studies as a kind of infection.
author: James Lindsay
date: '2020-05-30'
link: https://newdiscourses.com/2020/05/james-explains-what-about-sociology/
media_url: ''
title: 'James Explains: What About Sociology?'
---
<https://newdiscourses.com/2020/05/james-explains-what-about-sociology/>

- James introduces a series called “James Explains” to answer questions on Critical Social Justice and related topics through articles or podcasts.
- Received an email from Erek, a 34-year-old with a Bachelor's in Sociology, asking about James's views on Sociology, its legitimacy, and advice for future scholars.
- James responds, describing Sociology as complex and varied in its engagement with critical theory and postmodern epistemology.
- He notes that fields like gender studies and ethnic studies are highly influenced by critical theory, but Sociology has both critical and traditional-theory strands.
- Highlights sociologists like Bradley Campbell and Jason Manning, who oppose Critical Social Justice approaches, as examples of traditional-theory sociologists.
- Asserts that Sociology can be a legitimate field if pursued as a traditional theory focused on understanding society rather than critiquing it for change.
- Advises future sociologists to eschew critical methods, seek truth objectively, and not let activism lead their research.
- Calls for existing sociologists to reject critical theory, distance themselves from "grievance studies," demand rigor, and critique poor and biased work to protect the field's reputation.