---
abstract: I am also motivated to rationally improve health “equity” without throwing
  out the baby with all this critical bathwater.
author: James Lindsay
date: '2020-05-22'
link: https://newdiscourses.com/2020/05/james-explains-health-equity-babies-bathwater/
media_url: ''
title: Health Equity, Babies, & Bathwater
---
<https://newdiscourses.com/2020/05/james-explains-health-equity-babies-bathwater/>

- James introduces a series called "James Explains" to answer questions on Critical Social Justice and related topics through articles or podcasts.
- Received a note from Reneé, a doctor who observed health inequalities firsthand and studied them, expressing frustration with the mix of good concepts and what they perceive as extreme leftist ideology in the field.
- James agrees with Reneé's motivation to improve health equity without succumbing to what he describes as "woke" and "communist" ideologies.
- James believes it's possible to reduce health inequalities and inequities through realistic, evidence-based approaches that focus on fairness, equality, and a genuinely just society.
- Equity is differentiated from equality, with equity focusing on adjusting shares to achieve equal outcomes, which James finds sometimes justified but prefers equality of access.
- Critical Social Justice's approach to equity, according to James, is flawed due to its fundamental belief in systemic oppression and its refusal to acknowledge individual responsibility.
- James criticizes the approach to health equity during Covid-19, which includes prioritizing care based on race, as unrealistic and politically driven rather than genuinely aiming for healthcare equality.
- Economic disparities are seen as a major factor in health inequalities, with James suggesting that addressing economic issues could lead to better health equality.
- James advises Reneé to be a balanced voice in the field by focusing on truth and evidence, and to expect resistance from those entrenched in Critical Social Justice ideology.
- James concludes that reducing healthcare inequalities and some inequities is possible by focusing on practical solutions and evidence, despite potential opposition from ideological groups.