---
abstract: I feel I haven't done an adequate job explaining to people that what the
  Critical Social Justice scholars and activists have been building isn't a new intellectual
  order, it's a new alternative moral order.
author: James Lindsay
date: '2020-05-28'
link: https://newdiscourses.com/2020/05/liberalism-anti-liberal-moral-order/
media_url: ''
title: Liberalism and its Anti-liberal Moral Order
---
<https://newdiscourses.com/2020/05/liberalism-anti-liberal-moral-order/>

- Critical Social Justice (CSJ) is described not as a new intellectual order but as an alternative moral order, likened to a new religion with liberation from oppression as its core moral impulse.
- The origins of CSJ in Critical Theory aimed to introduce moral analysis into sciences and law, focusing on liberation and problematizing ideas based on moral grounds.
- CSJ seeks to replace liberal democracy with an "ideal democracy" free from oppression, drawing on Marxist, Freudian, and other theories to critique societal power structures.
- The concept of hegemony, from Antonio Gramsci, is central to CSJ, emphasizing the power dynamics that maintain societal structures.
- CSJ views all processes and methods as inherently non-neutral and morally charged, advocating for a liberationist perspective.
- The movement rationalizes actions like looting as responses to societal oppression, with its intellectual framework ("Theory") serving as a set of rationalizations or doctrine.
- CSJ is explicitly anti-liberal, critiquing liberalism as a facade that maintains dominant societal structures and discourages social revolution.
- The article argues that liberal societies, characterized by their tolerance and conflict management, are fundamentally different and superior to those based on particular moral orders like CSJ.
- Liberal societies allow for self-reformation and the coexistence of diverse moral orders, including anti-liberal ones, which is seen as a strength.
- CSJ's version of "tolerance" is likened to repressive tolerance, which does not allow for genuine dissent or deviation from its norms.
- The article concludes that understanding CSJ requires recognizing it as a repressive and dysfunctional moral order first, with its intellectual aspects serving mainly as rationalizations or disguises for its core moral impulses.