---
abstract: It’s virtually certain that a Biden administration will not maintain President
  Trump’s executive order that was issued in response to using Critical Race Theory
  in employee training circumstances in federal agencies and contractors.
author: James Lindsay
date: '2020-12-19'
link: https://newdiscourses.com/2020/12/maintaining-expanding-ban-critical-race-theory/
media_url: ''
title: Maintaining and Expanding the Ban on Critical Race Theory
---
<https://newdiscourses.com/2020/12/maintaining-expanding-ban-critical-race-theory/>

- The article discusses President Trump's Executive Order on Combating Race and Sex Stereotyping and anticipates its likely repeal under a Biden administration.
- Four main points are highlighted regarding the order and its implications:
  1. The order lacks protection at state and local levels, which is deemed necessary.
  2. It is criticized for not addressing other identity factors beyond race and sex, such as gender, sexuality, and disability status.
  3. There has been widespread misinformation about the order, with many falsely claiming it bans diversity or racial sensitivity training altogether.
  4. Critics of the order, including university officials, journalists, and Democratic politicians, are challenged to justify their opposition in terms of the specific "divisive concepts" the order prohibits.
- The article calls for action at state and local levels to implement similar protections and for critics to be held accountable for misrepresenting the order and for wanting to engage in the prohibited "divisive concepts."
- It emphasizes the need for clarity and accountability in discussing and implementing policies related to diversity training and critical race theory.