---
abstract: Most of the young people currently demolishing America’s statues were born
  too late to have picked up the habit from watching the attacks on statues of Lenin
  in the early 1990s, or of Saddam Hussein in the early 2000s.
author: New Discourses
date: '2020-09-02'
link: https://newdiscourses.com/2020/09/most-dangerous-place-to-be/
media_url: ''
title: The Most Dangerous Place To Be
---
<https://newdiscourses.com/2020/09/most-dangerous-place-to-be/>

- Young people demolishing statues in America likely influenced by college education emphasizing the revolutionary power of iconoclasm.
- Symbols are now seen as performative, actively altering reality, challenging objective facts and rational debate.
- Post-structuralist and performativity theories, like those of Judith Butler, argue aspects of identity such as gender are performative, leading to identity politics.
- The article questions the sudden dogmatic belief in symbols as performative and the impact of social media on young people's perception of reality.
- The concept of hyper-reality, where the world consists only of images without truth, is highlighted as a concern.
- The article references historical iconoclasm in Christianity and the Protestant Reformation, drawing parallels to current events.
- Academia's role in promoting postmodern views and abandoning objective truth is criticized.
- The article concludes with a warning about the potential consequences of current iconoclastic actions, drawing on historical examples of revolutionaries turning on their own.