---
abstract: Over the last few years, it has become apparent that, for whatever nobility
  and moral worth lies in the project called “social justice,” something has gone
  badly wrong with the ideological movement on the far left that repeatedly calls
  for—or, more accurately, demands—it.
author: James Lindsay
date: '2020-02-28'
link: https://newdiscourses.com/2020/02/naming-enemy-critical-social-justice/
media_url: ''
title: 'Naming the Enemy: Critical Social Justice'
---
<https://newdiscourses.com/2020/02/naming-enemy-critical-social-justice/>

- The article discusses the problematic aspects of the far-left ideological movement that demands social justice, highlighting how challenging it is to critique or oppose it due to its association with the inherently positive concept of social justice.
- It emphasizes that social justice is a core concern of progressive politics and liberalism, aiming to protect individuals from tyranny and ensure fairness and kindness in society.
- The movement, however, is criticized for becoming a menace and potentially tyrannical, with its critique of liberalism and free societies.
- The difficulty in naming and opposing this movement is explored, with terms like Social Justice Movement, Cultural Marxism, and Neo-Marxism being considered but found problematic.
- The article introduces the term "Critical Social Justice" as a more accurate descriptor, based on the work of educators Ozlem Sensoy and Robin DiAngelo, who distinguish their approach from mainstream social justice standpoints.
- Critical Social Justice is characterized by its reliance on critical theory, recognition of societal stratification and inequality, and a commitment to changing the fabric of society through activism.
- The movement is rooted in postmodernism and poststructuralism, viewing social injustices as real and structural, and demanding a lifelong commitment to activism from its adherents.
- The author argues that Critical Social Justice has co-opted the concept of social justice and proposes distinguishing between the two to challenge the ideology's anti-liberal and Neo-Marxist foundations.