---
abstract: Given the events of the past few months, it has probably been explained
  to you at least once that all people who are “white” and “white-adjacent” are allegedly
  complicit in “systemic racism.”
author: James Lindsay
date: '2020-07-09'
link: https://newdiscourses.com/2020/07/nobody-systemically-racist/
media_url: ''
title: Why Nobody is Systemically Racist
---
<https://newdiscourses.com/2020/07/nobody-systemically-racist/>

- The article discusses the concept of "white complicity" in systemic racism, as proposed by scholars of whiteness studies, suggesting that all white and "white-adjacent" individuals are complicit in systemic racism due to their enjoyment of benefits from "whiteness" and white privilege.
- It critiques the expansion of the definition of complicity by Barbara Applebaum in her book "Being White, Being Good," arguing that it unfairly assigns moral responsibility to individuals for their passive support of oppressive systems.
- The article uses an analogy of a tragic accident to illustrate the perceived flaws in Applebaum's reasoning, suggesting that her approach assigns blame too broadly and does not account for individual intent or direct participation in wrongdoing.
- It argues that systemic thinking, as applied by critical activist-scholars, muddles understanding of issues like racism and encourages symbolic contrition rather than meaningful action or personal growth.
- The article criticizes the concept of "systemic racism" for obscuring rather than clarifying issues of racism and for fostering guilt, shame, and moral confusion instead of encouraging genuine responsibility.
- It advocates for better approaches to assigning moral responsibility that focus on individual actions, intentions, and knowledge, rather than vague, systemic attributions of blame.