---
abstract: You proudly proclaim your racism in your writings, as so often racists do.
  We have read your work and can see the racism dripping from every page.
author: New Discourses
date: '2020-06-20'
link: https://newdiscourses.com/2020/06/open-letter-robin-diangelo-anti-racism/
media_url: ''
title: An Open Letter to Robin DiAngelo about "Anti-racism"
---
<https://newdiscourses.com/2020/06/open-letter-robin-diangelo-anti-racism/>

- The article is an open letter to Robin DiAngelo, criticizing her for promoting what the authors perceive as a divisive and harmful approach to addressing racism.
- The authors accuse DiAngelo of admitting to being racist in her writings and spreading racism through her work.
- They argue that DiAngelo's teachings on systemic racism and complicity in racism foster division and obsession with race, particularly among children.
- The letter expresses concern that DiAngelo's influence is leading to familial and societal discord.
- The authors reject the notion that the United States was built exclusively by or for any single racial or gender group, emphasizing a collective effort in the nation's development.
- They refuse to accept what they see as DiAngelo's redefinition of racism and her portrayal of interracial relationships as inherently oppressive.
- The letter concludes with a rejection of DiAngelo's ideas and a call for unity and individual decision-making in addressing racism.
- The signatories identify themselves as "professional brown Americans" who feel unable to reveal their names due to fear of repercussions.