---
abstract: Perhaps it was the lack of scholarly rigor on the part of the curators who
  failed to prove definitively that Guston was not a racist? That is not the case
  either.
author: New Discourses
date: '2020-12-01'
link: https://newdiscourses.com/2020/12/philip-guston-not-now-impact-argument/
media_url: ''
title: 'Philip Guston (Not) Now: The Impact Argument'
---
<https://newdiscourses.com/2020/12/philip-guston-not-now-impact-argument/>

- On October 1, 2020, Julia Friedman discusses the postponement of the "Philip Guston Now" retrospective initially set for summer 2020, delayed until 2024 by the National Gallery of Art, Boston MFA, Tate Modern, and Houston MFA due to concerns over Guston's KKK imagery.
- The decision, influenced by recent social and racial justice concerns, faced criticism for being an act of self-censorship and patronizing, leading to an open letter with over a thousand signatures demanding the exhibition's restoration.
- Critics argue the postponement overlooks Guston's anti-racist intentions and the curatorial work done to contextualize his imagery, suggesting a failure to engage with the artist's complex exploration of evil and societal issues.
- The article highlights Guston's personal history with racism and his artistic engagement with themes of social injustice, suggesting the exhibition's delay reflects a broader cultural shift towards prioritizing emotional safety over artistic merit and historical context.
- Developments since the article's writing include a defense of the postponement by the National Gallery's director, the suspension of Tate curator Mark Godfrey for criticizing the delay, and the eventual rescheduling of the retrospective for 2022 following backlash, though officials deny the backlash influenced the decision.