---
abstract: This rhetoric is, by design, meant to paint political dissidents as myopic
  stooges who are unwilling to “listen to the Lived Experiences of marginalized people,”
  thus making them unwittingly complicit in systems of oppression.
author: New Discourses
date: '2020-10-04'
link: https://newdiscourses.com/2020/10/poverty-lived-experiences/
media_url: ''
title: The Poverty of "Lived Experiences"
---
<https://newdiscourses.com/2020/10/poverty-lived-experiences/>

- Political dissidents often find themselves at odds with Woke Folk, particularly over the concept of "Lived Experiences," which is central to Woke Ideology.
- "Lived Experiences" are interpreted by Woke Folk as evidence of oppression, differing from mere empirical claims by adding a layer of subjective interpretation.
- The essay argues that this reliance on "Lived Experiences" is a strategy to adapt Woke ideology to environments that value evidence and reasoned argument, by making claims that are immune to traditional scrutiny.
- It contrasts empirical and phenomenological claims, likening the latter to literary criticism, where interpretations are subjective and not universally resolvable.
- The essay critiques Woke epistemology for its skepticism of objectivity and reliance on subjective interpretations, suggesting it undermines the standards of evidence and reasoned argument.
- It advises political dissidents on how to engage with Woke Folk by insisting on evidence and reasoned argument, and not accepting subjective interpretations as incontrovertible evidence.
- The essay concludes that dismantling the reliance on "Lived Experiences" can expose the weaknesses in Woke arguments, likening a Woke individual barred from using "Lived Experiences" to a fish out of water.
- The author suggests that understanding and countering Woke rhetorical strategies is crucial for political dissidents aiming to preserve the integrity of liberal democratic institutions.