---
abstract: Last year, Helen Pluckrose and I dedicated most of our time to writing a
  book about how “activist scholarship” has risen to prominence and created societal
  conditions that threaten to rip our societies apart.
author: James Lindsay
date: '2020-06-14'
link: https://newdiscourses.com/2020/06/principled-statement-opposition-critical-race-theory-excerpt-cynical-theories/
media_url: ''
title: 'A Principled Statement of Opposition to Critical Race Theory: An Excerpt from
  ''Cynical Theories'''
---
<https://newdiscourses.com/2020/06/principled-statement-opposition-critical-race-theory-excerpt-cynical-theories/>

- Helen Pluckrose and the author spent last year writing a book on the rise of "activist scholarship" and its societal impacts, focusing on postmodernism.
- Postmodernism is criticized for its radical skepticism about objective truth and its view that knowledge is merely a political assertion.
- The authors argue this philosophy underpins current societal divisions and conflicts.
- They advocate for principled opposition to such ideologies, emphasizing truth, depoliticization, and fairness over critical theories and radical skepticism.
- Their book, "Cynical Theories," aims to offer alternatives to critical theory critiques and postmodern skepticism, particularly in the context of race, gender, and identity.
- An excerpt from the book presents a principled statement opposing Critical Race Theory, affirming the need to address racism but criticizing the theory's approach as divisive and counterproductive.
- The authors encourage adopting principled statements to foster unity and address societal issues more effectively.
- "Cynical Theories" is available for pre-order and set to release on August 25, 2020.