---
abstract: En 2018, la "educadora de la blancura" Robin DiAngelo publicó un libro superventas
  llamado White Fragility. Este libro está destinado a enseñar a los blancos sobre
  su propio racismo.
author: James Lindsay
date: '2020-06-22'
link: https://newdiscourses.com/2020/06/problema-fragilidad-blanca/
media_url: ''
title: El Problema con la Fragilidad Blanca
---
<https://newdiscourses.com/2020/06/problema-fragilidad-blanca/>

- En 2018, Robin DiAngelo publicó "White Fragility", un libro dirigido a enseñar a los blancos sobre su propio racismo y cómo resisten aprender y desafiarlo debido a su "fragilidad blanca".
- DiAngelo redefine "racismo" y "supremacía blanca" como sistemas vagamente definidos, alejándose de la asociación con grupos de odio explícito como el Ku Klux Klan.
- Argumenta que ser "activamente antirracista" es un compromiso de por vida que requiere autorreflexión, autocrítica y activismo social, que ella enseña en seminarios costosos.
- Según DiAngelo, todos los blancos son automáticamente "racistas" debido a su posición social dominante y beneficio del racismo, independientemente de sus acciones individuales.
- La "fragilidad blanca" se describe como una incapacidad para aceptar acusaciones de racismo, lo que lleva a reacciones emocionales defensivas, y cualquier negación se ve como evidencia de racismo.
- DiAngelo también critica a las personas de otras razas que participan en la "cultura blanca", acusándolas de complicidad en el racismo.
- La autora admite que su definición de racismo difiere de la comprensión común, pero argumenta que su enfoque es necesario para abordar el racismo sistémico.
- La crítica principal al concepto de "fragilidad blanca" es que convierte cualquier acusación de racismo en imposible de negar, funcionando como un chantaje moral y emocional.
- DiAngelo promueve su programa de antirracismo como la única solución válida, lo que ha llevado a acusaciones de que su trabajo es más un negocio lucrativo que un esfuerzo genuino por combatir el racismo.
- El concepto de "fragilidad blanca" se basa en las observaciones personales de DiAngelo y no en estudios académicos rigurosos, lo que plantea dudas sobre su validez científica.