---
abstract: Pseudo-realities, being false and unreal, will always generate tragedy and
  evil on a scale that is at least proportional to the reach of their grip on power—which
  is their chief interest—whether social, cultural, economic, political, or (particularly)
  a combination of several or all of these.
author: James Lindsay
date: '2020-12-25'
link: https://newdiscourses.com/2020/12/psychopathy-origins-totalitarianism/
media_url: ''
title: Psychopathy and the Origins of Totalitarianism
---
<https://newdiscourses.com/2020/12/psychopathy-origins-totalitarianism/>

- The article discusses the concept of ideological pseudo-realities, false constructions of reality that lead to societal tragedies.
- Pseudo-realities are maintained by power, coercion, and manipulation, often by psychopathic individuals for their advantage.
- These false realities replace common sense and science with distorted interpretations designed to uphold power structures.
- Pseudo-realities are linguistic phenomena, requiring social enforcement and often leading to totalitarianism.
- They are constructed to favor a small fraction of the population with pathological limitations, projecting their psychopathologies onto normal people.
- Normal people misinterpret the motivations of those ensnared by pseudo-realities, often until it's too late.
- Pseudo-realities recruit adherents through manipulation of psychological weaknesses and exploit the tolerant and charitable nature of communities.
- The ultimate purpose of creating a pseudo-reality is to gain power, often through double standards, linguistic traps, and demoralization.
- Ideological pseudo-realities are distinguished from general ideologies by their reliance on a constructed false reality and their cult-like nature.
- They often lead to Utopian visions that justify present injustices with the promise of a perfect future society.
- Pseudo-realities arise from abuses of language that enable abuses of power, targeting the educated upper-middle class for recruitment.
- They employ a paralogic (false logic) and a paramorality (false morality) to manipulate and enforce adherence.
- The spread of a pseudo-reality results in the psychopathologization of otherwise normal people, turning them into functional psychopaths.
- Resistance to pseudo-realities involves awareness, refusal to participate, and exposing their contradictions and immorality.
- Effective resistance can restore epistemic and moral authority to normal people, undermining the pseudo-reality's power.