---
abstract: Critical Race Theory proceeds upon a number of core tenets, the first and
  most central of which is that racism is the ordinary state of affairs in our society.
author: James Lindsay
date: '2020-10-19'
link: https://newdiscourses.com/2020/10/racial-healing-reject-critical-race-theory/
media_url: ''
title: For Racial Healing, Reject Critical Race Theory
---
<https://newdiscourses.com/2020/10/racial-healing-reject-critical-race-theory/>

- The article discusses the discomfort a shop owner might feel when deciding which customer to serve first, influenced by Critical Race Theory (CRT).
- CRT has become mainstream and posits that racism is ordinary and present in all societal interactions.
- The theory suggests that in any situation involving people of different races, racism is assumed to be present, and the task is to identify and dismantle it.
- The article presents a scenario where serving either a black or white customer first could be interpreted as racist, according to CRT.
- It argues that CRT's assumption of pervasive racism leaves no room for a correct choice in such everyday situations.
- The author believes that CRT's approach is counterproductive to achieving racial healing and a more just society.
- The article concludes that rejecting CRT is necessary for societal progress towards ending racism and fostering fairness.