---
abstract: As unlikely as it seems, a highly obscure academic theory known as Critical
  Race Theory has completely mainstreamed in society, and now everyone is discussing
  it.
author: James Lindsay
date: '2020-06-12'
link: https://newdiscourses.com/2020/06/reasons-critical-race-theory-terrible-dealing-racism/
media_url: ''
title: Eight Big Reasons Critical Race Theory Is Terrible for Dealing with Racism
---
<https://newdiscourses.com/2020/06/reasons-critical-race-theory-terrible-dealing-racism/>

- Critical Race Theory (CRT) has become a mainstream topic of discussion, despite its complex academic origins.
- CRT posits that racism is inherent in all aspects of life and society.
- It operates on several controversial principles, including the belief that racism benefits white people, skepticism towards free societies, and the rejection of individualism in favor of viewing people solely by their racial group.
- CRT criticizes the use of science, reason, and evidence as "white" ways of knowing, promoting storytelling and lived experience as alternatives.
- It dismisses all potential alternatives to its approach, such as colorblindness, labeling them as forms of racism.
- CRT is intolerant of dissent, even from within racial minority groups, suggesting that disagreement with its tenets is rooted in racism or white supremacy.
- The theory is described as insatiable, with its demands and grievances being unending and impossible to fully satisfy.
- The article argues that CRT is a detrimental approach to addressing race issues and racism, advocating for better alternatives.