---
abstract: The “walking on eggshells” feeling causes you to ‘go along to get along.’
author: New Discourses
date: '2020-11-24'
link: https://newdiscourses.com/2020/11/road-hell-paved-with-eggshells/
media_url: ''
title: The Road to Hell is Paved with Eggshells
---
<https://newdiscourses.com/2020/11/road-hell-paved-with-eggshells/>

- In late 2018, Kelsey Baker left an emotionally abusive relationship and shared her experience on Facebook, highlighting the non-physical forms of abuse she endured.
- Her post, which described the emotional manipulation and control she faced, resonated with many, receiving over 134,000 shares and 17,000 comments of support and empathy.
- The article discusses the widespread nature of emotional abuse, emphasizing that it is driven by the abuser's need for power and control, often through tactics like constant criticism, isolation, and reality distortion.
- Victims of emotional abuse may struggle to recognize or leave abusive situations due to factors like dependency, low self-worth, and isolation.
- The piece also explores how toxic cultures, whether in organizations or broader society, can perpetuate abuse and silence dissent, drawing parallels between personal experiences of abuse and the culture within The New York Times as described by former writer Bari Weiss.
- It concludes by reflecting on the pervasive fear of expressing dissenting views in today's society, suggesting that many feel compelled to self-censor in the face of potential backlash, likening the social climate to walking on eggshells.