---
abstract: Woke culture continues to become ever-more relevant to people in all walks
  of life, and this led to a recent BBC audio-documentary featuring feminist authort
  Helen Lewis and produced by Craig Templeton Smith, “The Roots of ‘Woke’ Culture.”
author: New Discourses
date: '2020-03-24'
link: https://newdiscourses.com/2020/03/roots-woke-culture/
media_url: ''
title: The Roots of "Woke" Culture
---
<https://newdiscourses.com/2020/03/roots-woke-culture/>

- The BBC audio-documentary "The Roots of ‘Woke’ Culture" explores the origins and implications of woke culture.
- Hosted by feminist author Helen Lewis and produced by Craig Templeton Smith.
- The documentary examines the academic roots of woke culture in the theoretical humanities, particularly within "Grievance Studies."
- Features discussions with academics and commentators like James Lindsay, Peter Boghossian, Helen Pluckrose, Konstantin Kisin, and Toby Young.
- The "hoax" trio (Lindsay, Boghossian, Pluckrose) argue that woke culture is deeply influenced by postmodern theory and the New Left's radical activism, focusing on identity politics and social grievances.
- Other scholars interviewed offer differing perspectives.
- The documentary invites listeners to consider whether woke culture is a product of postmodern theory and identity politics.