---
abstract: When it comes to our children's schools, many of us will conclude that it's
  necessary and important in our modern, progressive world for our children to learn
  about these sorts of issues.
author: James Lindsay
date: '2020-10-17'
link: https://newdiscourses.com/2020/10/schools-teaching-kids-social-justice/
media_url: ''
title: Why Schools Are Teaching Our Kids "Social Justice"
---
<https://newdiscourses.com/2020/10/schools-teaching-kids-social-justice/>

- The article discusses the ideology of "Wokeness" and Critical Social Justice (CSJ), emphasizing its deep-rooted beliefs and mission rather than seeing it as a benign interest in social issues like racism, sexism, and transgender rights.
- It argues that many people misunderstand CSJ as well-intentioned, failing to see its comprehensive worldview that aims to "awaken" people to perceived systemic oppressions.
- The article highlights the goal of CSJ in education: to instill a "critical consciousness" in students, making them view society through the lens of identity-based power systems and injustices that need disrupting.
- It points out that subjects like mathematics and history are being reinterpreted to focus on systemic oppression and racism, citing examples like "ethnomathematics" in Washington and a proposed but rejected curriculum in California that would have taught history as "hxrstory."
- The article criticizes the approach of teaching children to view every aspect of society, including science and mathematics, through a pessimistic and divisive perspective focused on identity politics.
- It concludes that introducing CSJ into education is not benign but a deliberate attempt to reshape children's understanding of society in a narrow and divisive way.
- An editor's note clarifies that the proposal to rename "history" to "hxrstory" in California was rejected.