---
abstract: As unlikely as it seems, a highly obscure academic theory known as Critical
  Race Theory has completely mainstreamed in society, and now everyone is discussing
  it.
author: James Lindsay
date: '2020-06-13'
link: https://newdiscourses.com/2020/06/sharing-size-nine-reasons-critical-race-theory-terrible-dealing-racism/
media_url: ''
title: 'Sharing Size: Nine Reasons Critical Race Theory Is Terrible for Dealing with
  Racism'
---
<https://newdiscourses.com/2020/06/sharing-size-nine-reasons-critical-race-theory-terrible-dealing-racism/>

- Critical Race Theory (CRT) posits that racism is inherent in all aspects of life, leading its proponents to seek out racism in every interaction and institution.
- CRT operates on the principle of "interest convergence," suggesting that actions by racially privileged groups are inherently self-serving, making genuine anti-racist actions impossible under its framework.
- CRT is critical of liberal, free societies, advocating for restrictions on free speech and opposing ideals like individualism and meritocracy, viewing them as mechanisms of racial oppression.
- Under CRT, individuals are primarily seen as representatives of their racial groups rather than as individuals, dismissing the significance of personal identity and achievements.
- CRT is skeptical or hostile towards science, viewing it as a product of white, Western culture and thus inherently biased against non-white groups.
- CRT rejects any approach that diminishes the focus on race, such as colorblindness, arguing that race should be central to all societal analysis and interaction.
- CRT dictates a specific way of thinking about race, to the extent that even black individuals who diverge from its tenets can be ostracized or labeled as betraying their racial identity.
- CRT is described as insatiable, rejecting all alternatives and incapable of being satisfied or proven wrong, thus perpetuating a cycle of division and tension.
- The article argues that CRT exacerbates division and harms those it aims to help, suggesting that there are better ways to address racism and societal issues.