---
abstract: As you will see, a very common problem is that people think Critical Race
  Theory is one thing when it is really another, and good-intentioned people tend
  to adopt it without realizing what it is (and reject it when they do know what it
  is).
author: James Lindsay
date: '2020-06-09'
link: https://newdiscourses.com/2020/06/template-resisting-white-fragility-workplace/
media_url: ''
title: A Template for Resisting White Fragility in the Workplace
---
<https://newdiscourses.com/2020/06/template-resisting-white-fragility-workplace/>

- The article shares a note from someone thanking the author for helping them convince their workplace not to adopt Critical Race Theory (CRT).
- The person's boss had considered using "White Fragility" as a discussion starter, but the employee used information from the author to argue against CRT, describing it as racist and divisive.
- The author expresses concern about the dangers of incorporating CRT and similar ideas into organizations, suggesting they can damage corporate culture and increase division.
- The note to the boss outlines the employee's issues with the white fragility/Robin DiAngelo model, including its promotion of racism, division, cancel culture, and victimhood.
- The employee argues that the organization should avoid this model to serve clients more holistically and respect diverse opinions and backgrounds.
- The note criticizes the redefinition of racism by CRT, contrasting the traditional dictionary definition with CRT's more complex and politically charged definition.
- The employee expresses concern that CRT's definition of racism makes constructive conversation difficult, divides people by skin color, and perpetuates a narrative of powerlessness and supremacy.
- The note concludes by questioning the necessity of name-calling to address systemic injustice, suggesting it's possible to recognize and correct injustices without resorting to such tactics.