---
abstract: 'Here’s a pretty simple truth that keeps getting harder to believe: you
  don’t have to be an activist—not for a cause, not for a party, not for anything.'
author: James Lindsay
date: '2020-06-15'
link: https://newdiscourses.com/2020/06/white-silence-not-violence/
media_url: ''
title: White Silence is NOT Violence
---
<https://newdiscourses.com/2020/06/white-silence-not-violence/>

- The article discusses the pressure on individuals, particularly white people, to become activists, driven by slogans like "white silence is violence."
- It traces this pressure back to Critical Theory and its evolution, which initially aimed to understand the rise of fascist regimes and later focused on the idea of complicity in societal evils.
- Herbert Marcuse, a notable Critical Theorist, is mentioned for his views on tolerance and complicity, advocating for a form of "repressive tolerance."
- Barbara Applebaum's book "Being White, Being Good" is highlighted for arguing that all white people are complicit in racism and white supremacy due to systemic benefits, pushing for a lifelong commitment to "anti-racism" activism.
- The article critiques the extreme interpretations of complicity and violence within these theories, suggesting that they serve more as emotional manipulation than realistic calls to action.
- It concludes that individuals should not feel compelled to adopt activism based on exaggerated claims and that the slogan "white silence is violence" is an attempt at compelled speech rather than a genuine call for justice.