---
abstract: Relativism contends that all truth is relative except for the claim that
  “truth is relative.”
author: New Discourses
date: '2020-11-12'
link: https://newdiscourses.com/2020/11/why-world-cultural-relativism-descendents/
media_url: ''
title: 'Why the World is the Way It Is: Cultural Relativism and Its Descendents'
---
<https://newdiscourses.com/2020/11/why-world-cultural-relativism-descendents/>

- Relativism posits that truth is historically conditioned and does not transcend cultural boundaries, making all truth relative.
- Cultural relativism claims each culture has its own valid mode of perception and moral code, denying universal moral truths.
- Cultural relativism leads to moral equivalence, suggesting we cannot judge or impose values on other societies, even in extreme cases like Nazism or apartheid.
- Intellectual movements like multiculturalism, racism, postmodernism, deconstructionism, political correctness, and social engineering are seen as descendants of cultural relativism.
- Philosophers like David Hume, Immanuel Kant, and others contributed to the development of relativism and its offshoots, challenging the concepts of objective knowledge and universal moral truths.
- Multiculturalism, as a form of cultural relativism, rejects universal truths and norms, emphasizing the equal value of all cultures but often excluding the Western perspective.
- Racism, within the context of multiculturalism, is criticized as determining identity by race, which undermines individual merit and responsibility.
- Political correctness, stemming from multiculturalism, seeks to regulate language to avoid offending specific groups, often at the expense of clarity and truth.
- Deconstructionism and postmodernism challenge the idea of fixed meanings and universal truths, promoting a view of reality as socially constructed and inherently pluralistic.
- Social engineering, influenced by cultural relativism, aims to achieve economic equality and address historical victimization through elite intervention, often disregarding individual differences and freedoms.
- The article argues that Western culture is objectively superior based on its life-affirming core values, such as reason, individualism, and the promotion of freedom and innovation.