---
abstract: It is irresponsible to the point of negligence for an organization or institution
  to adopt an environment that uses "diversity" training rooted in Critical Social
  Justice Theories like Critical Race Theory.
author: James Lindsay
date: '2020-11-16'
link: https://newdiscourses.com/2020/11/why-your-organization-should-not-do-diversity-training/
media_url: ''
title: Why Your Organization Should Not Do Diversity Training
---
<https://newdiscourses.com/2020/11/why-your-organization-should-not-do-diversity-training/>

- Employers and leaders are free to choose diversity training, including those based on Critical Race Theory (CRT) and Critical Social Justice (CSJ), but should be aware of the implications.
- The author argues that using "diversity" training rooted in CRT and CSJ is irresponsible and potentially negligent due to the risk of creating division and conflict within organizations.
- "Diversity" training is claimed to be designed to foster divisions, increase sensitivity to certain issues, and promote a zero-sum view of conflict, leading to a hostile work or learning environment.
- The training aims to create an activist core within the organization, sympathetic adopters of the ideas, and a general awareness of "diversity" concepts, while silencing or discrediting opposition.
- The eventual outcome of such training is predicted to be organizational "civil war," with divisions between "racists" and "anti-racists" based on the training's ideology.
- The author contends that "diversity" training does not aim to improve organizational function but to further the goals of "diversity," even at the cost of the organization's collapse or diversion of its resources.
- Critical Theories, according to the author, do not build or improve but are designed to critique and dismantle, leading to either the failure of organizations that adopt them or their transformation into entities focused solely on "diversity."
- The article warns that "diversity" training can lead to financial failure, organizational collapse, or a shift in mission towards "diversity" at the expense of the original goals, with compliant executives replacing those not aligned with this mission.