---
abstract: The genesis of injustice.
author: James Lindsay
date: '2020-09-01'
link: https://newdiscourses.com/2020/09/woke-creation-myth/
media_url: ''
title: The Woke Creation Myth
---
<https://newdiscourses.com/2020/09/woke-creation-myth/>

- Initially, the world was described as a place of equal power among diverse cultures, despite prevalent violence and oppression, termed the Garden of Even.
- Europeans, sharing similar violent behaviors but distinguished by curiosity, rediscovered ancient knowledge during the Renaissance, leading them to seek more power.
- This pursuit of knowledge and power marked the beginning of systemic injustice, as Europeans left the Garden of Even, considering themselves superior and initiating colonialism.
- European colonialism spread systemic oppression worldwide, subjugating diverse cultures through force, disease, and the imposition of European culture and knowledge.
- Europeans, particularly white Western men, declared themselves the default, superior culture, leading to the global dominance of racism, sexism, misogyny, ableism, and Eurocentrism.
- The narrative concludes that the white, Western male's belief in his own superiority and the imposition of his standards as universal truths have replaced justice with systemic oppression.