---
abstract: 'Here are two important ideas that currently exist in fundamental opposition
  to one another: “Reasonableness” and “Wokeness.”'
author: James Lindsay
date: '2020-11-18'
link: https://newdiscourses.com/2020/11/wokeness-threatens-rule-of-law/
media_url: ''
title: Wokeness Threatens the Rule of Law
---
<https://newdiscourses.com/2020/11/wokeness-threatens-rule-of-law/>

- The article discusses the fundamental opposition between "Reasonableness" and "Wokeness" in the context of advanced legal systems.
- "Reasonableness" relies on the "reasonable-person standard," asking what a reasonable person would do in a given situation.
- "Wokeness" or "Critical Social Justice Theory" emphasizes radical subjectivism and the idea that reason is a tool of dominant power structures, dismissing the concept of a "reasonable person."
- The article argues that these ideologies are incompatible, posing a threat to the rule of law and equal rights in liberal societies.
- It highlights the concern that if "Wokeness" gains enough power, it could replace reasonableness with Critical Theories focused on identity and systemic power, fundamentally altering the legal system.
- The article mentions specific examples like Critical Race Theory and California's Proposition 16 to illustrate how these ideologies could reshape legal principles around concepts of systemic oppression and identity politics.
- It concludes by advocating for reason and warning against the potential for a totalitarian ideology under the guise of "Woke Law."