---
abstract: I can’t tell you how many times I’ve been asked why it is that the Woke
  won’t seem to have a debate or discussion about their views.
author: James Lindsay
date: '2020-07-30'
link: https://newdiscourses.com/2020/07/woke-wont-debate-you-heres-why/
media_url: ''
title: No, the Woke Won’t Debate You. Here's Why.
---
<https://newdiscourses.com/2020/07/woke-wont-debate-you-heres-why/>

- The article discusses why individuals who subscribe to Woke ideology and Critical Social Justice Theory often refuse to engage in debates or discussions about their views.
- It argues that this reluctance is not due to a fear of being exposed as fraudulent but is rooted in a comprehensive and fundamentally different worldview that includes its own ethics, epistemology, and morality, which is distinctly non-liberal.
- Critical Social Justice adherents believe the system is inherently rigged against them due to systemic oppression that permeates all aspects of society, including the ways knowledge and truth are constructed and recognized.
- They view traditional tools of debate and discussion, such as reason, rationality, and evidence, as part of the oppressive system they oppose. Instead, they favor methods like storytelling and appealing to emotions and lived experiences.
- The article outlines a "metaphysics of discourses," influenced by postmodernist thought, particularly Michel Foucault, which posits that power structures society through discourses. Engaging in debate with those who support dominant discourses is seen as dangerous and counterproductive to their goals.
- Critical Social Justice Theory holds that disagreement with their views is inherently illegitimate, stemming from either a false consciousness or a willful intention to oppress. Genuine disagreement can only come from within a Critical Theory perspective.
- The ideology also views association with those who hold systemic power and privilege as morally reprehensible, equating it with supporting racism, misogyny, and other forms of bigotry.
- Adherents often express feeling exhausted by the constant battle against systemic oppression, viewing invitations to debate as exploitative and reinforcing the dominance they fight against.
- The article concludes that expecting Critical Social Justice advocates to value or engage in debate and dialogue is a fundamental misunderstanding of their ideology, which rejects the foundational principles of liberalism and aims to dismantle the entire system in favor of Critical Theory.