---
abstract: Almost everybody has a Woke Breaking Point. A point of Peak Woke. Or, at
  least, they should.
author: James Lindsay
date: '2020-06-25'
link: https://newdiscourses.com/2020/06/woke-breaking-point/
media_url: ''
title: The Woke Breaking Point
---
<https://newdiscourses.com/2020/06/woke-breaking-point/>

- The article discusses the concept of a "Woke breaking point," a threshold at which individuals recognize that the Woke (Critical Social Justice) movement has gone too far.
- It highlights the importance of individuals establishing their own lines that should not be crossed by the movement, suggesting that this can prevent them from rationalizing extreme actions or ideologies after the fact.
- The rapid spread and some extreme aspects of Woke ideology are described as potentially leading to a totalitarian nightmare, with the author expressing concern over the movement's support by good and decent people.
- The author suggests asking people what it would take for them to acknowledge that the Woke movement has exceeded acceptable bounds, aiming to make them consider the possibility of the movement going too far and to identify their non-negotiable limits.
- The article recounts personal experiences and observations of the author and their friend, noting instances where they or others reached their breaking points due to perceived excesses of the movement, such as unfair accusations, attacks on science, real racism, and the defense of riots.
- It also mentions broader societal concerns raised by others, including the tearing down of statues, job losses, and the impact on personal relationships, as indicators that the movement has gone too far.
- The author advises that while initiating conversations about Woke breaking points may not be well-received, it is crucial for individuals to reflect on their principles and establish boundaries to prevent rationalizing unacceptable actions or ideologies in the future.
- The article emphasizes the importance of asking challenging questions about what extremes would need to occur for someone to recognize the movement's overreach, suggesting that even personal or selfish considerations are valid starting points for reflection.