---
abstract: This isn't empowerment. It's disempowerment, even if we discount the other
  costs of such a not-at-all-racist doctrine.
author: James Lindsay
date: '2020-06-25'
link: https://newdiscourses.com/2020/06/wokeness-not-racist-doctrines-disempowerment/
media_url: ''
title: Wokeness and Its Not-at-all-racist Doctrines of Disempowerment
---
<https://newdiscourses.com/2020/06/wokeness-not-racist-doctrines-disempowerment/>

- Thomas Sowell's views on racism and personal responsibility contrast sharply with Critical Race Theory (CRT), which he criticizes for perpetuating a victimhood mentality among black people and other "minoritized" races.
- CRT aims to empower these groups by acknowledging systemic oppression but, according to critics, ends up disempowering them by denying their agency and reinforcing a permanent victim status.
- Sowell emphasizes individual responsibility, which CRT advocates see as a denial of systemic factors and victimhood, leading to significant criticism of Sowell.
- The article discusses the concept of agency within CRT, arguing that it views agency as something systematically denied to non-white people by a dominant white culture that values traits like reason, science, and civility as inherently "white."
- CRT posits that non-white individuals can only gain agency by adopting a "Woke" critical consciousness, rejecting their imposed "whiteness," or being seen as complicit in their own oppression.
- The discussion extends to the idea that white people, too, are victims of the system they benefit from, being morally responsible for systemic racism without being individually bad unless they reject anti-racism efforts.
- The article critiques the notion that adopting a critical consciousness or "Wokeness" actually removes agency by forcing individuals to conform to the expectations of their identity groups as defined by CRT, rather than allowing for individuality.
- It argues that CRT's focus on collective identity over individuality, and its requirement for total alignment with its principles, represents a form of totalitarian submission.
- The ultimate goal of CRT, according to the article, is to make everyone aware of their racial identity and the systemic racism that supposedly defines it, demanding a rejection of "whiteness" as part of achieving social justice.
- The article concludes that CRT's approach to addressing racism is flawed because it demands total adherence to its worldview, defers responsibility away from its adherents, and seeks to dismantle the concept of individual agency in favor of a collective identity politics.