---
abstract: As a theory of “political economy,” Marxism isn’t at all complicated. At
  the very bottom, it is the belief that human beings are fundamentally social beings
  whose true nature shapes and is shaped by their societies.
author: James Lindsay
date: '2022-11-01'
link: https://newdiscourses.com/2022/11/crt-queer-theory-and-marxism-by-any-other-name/
media_url: ''
title: CRT, Queer Theory, and Marxism by Any Other Name
---
<https://newdiscourses.com/2022/11/crt-queer-theory-and-marxism-by-any-other-name/>

- Marxism is a theory of political economy that views humans as fundamentally social beings whose nature is shaped by and shapes society.
- It posits two main ideas: the division of society through private property, where some claim exclusive rights to property, shaping society to benefit themselves; and a dynamic relationship between praxis (the ability to shape society) and its inversion, suggesting a continuous loop where society and individuals shape each other.
- Marxism argues that systemic injustice is created by those with exclusive access to private property, leading to a society organized for their benefit, perpetuating their ideology and maintaining their power.
- The theory advocates for societal revolution from the margins to overthrow this unjust state, emphasizing conscious action to change society's direction towards communism, where private property and thus dehumanization are abolished.
- Marxism is not just descriptive but aims to change society, focusing on historical purpose and class conscientization to mobilize the oppressed to seize the means of production and transform society.
- The article extends Marxist analysis to various forms of identity politics, suggesting that Marxism can adapt to critique different forms of exclusive property beyond economic capital, such as race, gender, sexuality, ability, and body size, leading to theories like Critical Race Theory, (Marxian) Feminism, Queer Theory, Disability Studies, and Fat Studies.
- These theories argue that societal structures and ideologies advantage certain groups while exploiting and disenfranchising others, advocating for awareness and collective action to achieve equity and justice across different dimensions of identity.
- Understanding Marxism and its adaptations is crucial for recognizing and combating its influence in society, aiming to prevent its goal of seizing the means of production and fundamentally altering society.