---
abstract: One of the “key goals” of the Woke Marxist movement is to "decenter the
  natural sciences." How on Earth is someone supposed to “decenter” the natural sciences—and
  from what, and why?
author: James Lindsay
date: '2022-11-08'
link: https://newdiscourses.com/2022/11/how-to-kill-a-science-the-process-of-dialectical-inversion/
media_url: ''
title: 'How to Kill a Science: The Process of Dialectical Inversion'
---
<https://newdiscourses.com/2022/11/how-to-kill-a-science-the-process-of-dialectical-inversion/>

- The article discusses the goal of the Woke Marxist movement to "decenter the natural sciences" to elevate "other ways of knowing" and Marxist scientism to a position of credibility and authority.
- Decentering science involves shifting its central position of credibility and authority to make room for alternative "knowledges."
- The process of decentering is achieved through a dialectical inversion, which includes obscuring the epistemological superiority of scientific knowledge and attacking it on moral grounds.
- Dialectical inversion involves a two-step process: first, equating scientific knowledge with other forms of knowledge through a dialectical sublation, and then morally inverting the value of these knowledges to favor activism.
- The article explains the concept of dialectical sublation as understanding two opposing things as part of a singular whole from a higher perspective.
- It criticizes the manipulation of science for ideological purposes, describing it as a process of "sciencecide" where science is attacked and replaced with ideologically driven "knowledge."
- The article argues that this strategy relies on moral bullying and the claim to a higher consciousness by activists, who position their knowledge as morally superior.
- It warns against the dangers of allowing this ideological takeover of science, emphasizing the importance of defending the epistemological superiority of scientific knowledge.
- The author advises standing firm against attempts to subvert science with ideology, highlighting the need to expose and reject these efforts to maintain the integrity of scientific disciplines.