---
abstract: There’s a great and frustrating irony about Marxism. On the one hand, it
  is extremely simple—almost cartoonishly so. On the other hand, millions of pages
  of extremely complicated writing exist trying to make it true.
author: James Lindsay
date: '2022-10-04'
link: https://newdiscourses.com/2022/10/many-faces-of-marxism/
media_url: ''
title: The Many Faces of Marxism
---
<https://newdiscourses.com/2022/10/many-faces-of-marxism/>

- Marxism is both simple and complex, with vast writings attempting to validate its principles.
- It is not merely an economic or social theory but a deeper belief system using these theories as components.
- Marxism is fundamentally a theory of man and the world, positing that man creates society, which in turn shapes man.
- It views society as stratified by those who have access to special forms of property (capital) and those who do not, leading to alienation and estrangement.
- Communism is seen as the solution to this estrangement, aiming for the abolition of private property to restore man to his 'true' social nature.
- Various forms of Marxism (Cultural, Critical, Postmodern, etc.) apply this framework to different aspects of society, identifying specific forms of 'special property' and advocating for their abolition.
- Marxism is critiqued as a cult-religious ideology focused on transforming the world by undoing perceived falls into stratified power dynamics.
- Understanding Marxism is essential for addressing its influence and restoring liberty and goodness to society.