---
abstract: According to Karl Marx, Communism, true and proper, is the self-conscious
  solution to “the riddle of history.”
author: James Lindsay
date: '2022-10-18'
link: https://newdiscourses.com/2022/10/riddle-of-history-solved/
media_url: ''
title: The Riddle of History, Solved
---
<https://newdiscourses.com/2022/10/riddle-of-history-solved/>

- Karl Marx viewed Communism as the solution to the "riddle of history," which he saw as the issues arising from private property and the division of labor.
- The article criticizes this view, arguing that history is not a riddle and that attempts to implement Marx's vision have led to failure and suffering.
- It suggests that the concept of "productive socialism" is an oxymoron, as historical attempts at socialism have failed to be productive or deliver on their promises.
- The article discusses the shift towards "sustainable capitalism" as a new branding for similar ideas, which still aim to eliminate private property and change societal values.
- It links these ideas to Herbert Marcuse's critiques of capitalism and his suggestions for a society that transcends the need for excessive consumption through a form of socialism.
- The piece argues that both "sustainable capitalism" and what it terms "productive socialism" are essentially the same, representing a modern form of Communism that seeks to control and restructure society.
- It concludes by urging a rejection of these ideas, advocating for a return to living history without trying to solve it as if it were a riddle, and emphasizing individual choice and refusal of these ideologies.