---
abstract: The learning loss that follows from a “critical” education into "social
  and emotional learning" represents nothing short of an intentional theft of education
  from our children and our society.
author: James Lindsay
date: '2022-09-12'
link: https://newdiscourses.com/2022/09/theft-american-education/
media_url: ''
title: The Theft of American Education
---
<https://newdiscourses.com/2022/09/theft-american-education/>

- "Learning loss" is often discussed in the context of the Covid-19 pandemic but is also attributed to failures in educational policy and practice.
- A significant learning loss in America is linked to educational approaches focusing on "equity" and "social justice," which prioritize teaching from a Woke Marxist perspective over traditional academic subjects.
- This form of learning loss is described as an intentional "theft of education," utilizing "critical pedagogy" developed from Marxist ideas by Paulo Freire and others, aiming to transform education to reproduce Marxist ideologies.
- Critical pedagogy involves connecting with students in a "democratic classroom" to identify "generative themes" from their lives, which are then used to engage students in political radicalization rather than traditional learning.
- The process involves "codification" of these themes into lesson plans that appear academic but are designed for political radicalization, leading to a "decodification" process where academic learning is overshadowed by political engagement.
- Experiments with Freirean methodology, such as in Nigeria, have shown that this approach can lead to emotional distress and a lack of interest in academic learning, as students become more focused on political action.
- The article argues that Freirean or critical education is not true education but a form of political indoctrination that steals genuine educational opportunities from students and should be removed from the education system.