---
abstract: Currently, there are just three terms that have been profoundly subverted
  and are being used to transform our society by Communists for Communist ends.
author: James Lindsay
date: '2022-09-01'
link: https://newdiscourses.com/2022/09/three-terms-communists-redefined-to-subvert-society/
media_url: ''
title: Three Terms Communists Redefined to Subvert Society
---
<https://newdiscourses.com/2022/09/three-terms-communists-redefined-to-subvert-society/>

- Over the past two years, many Americans have realized that the "Dialectical Left," including Communists, strategically change the meanings of words to achieve their agendas.
- This tactic becomes counterproductive once recognized, as it is manipulative and can be resisted by demanding clear definitions.
- The Dialectical Left, or Woke Marxists, have significantly altered the meanings of "inclusion," "democracy," and "citizenship" to transform society for Communist ends.
- Critical Theory, from the Frankfurt School, is used to reframe concepts in Marxist terms, focusing on power dynamics and structural analysis.
- Terms like "justice" and "education" are redefined to emphasize structural disadvantages and promote a political education aligned with Marxist Theory.
- "Inclusion" is misused to mean that societies must actively include those considered excluded by unjust power dynamics, often leading to the exclusion of others.
- "Democracy" is reinterpreted as "inclusive democracy," where true democracy is seen as achievable only under Communism, with current capitalist democracies viewed as inherently flawed.
- "Citizenship" is critiqued to mean "inclusive citizenship," where full citizenship is contingent on addressing structural disenfranchisements, leading to a redefinition of the social contract to advantage Leftism.
- Klaus Schwab of the World Economic Forum aims to rewrite global social contracts to prioritize sustainability and inclusivity, aligning with Marxist goals of global and inclusive citizenship.