---
abstract: Scientific Gnosticism is perhaps the most calamitous ideological phylum
  human beings have so far managed to contrive.
author: James Lindsay
date: '2021-08-19'
link: https://newdiscourses.com/2021/08/calamity-scientific-gnosticism/
media_url: ''
title: The Calamity of Scientific Gnosticism
---
<https://newdiscourses.com/2021/08/calamity-scientific-gnosticism/>

- The article posits that the current ideological turmoil can be classified within a biological taxonomical hierarchy, with Gnosticism at the kingdom level.
- It suggests that Critical Whiteness Studies, Critical Race Theory, and neo-Marxism fall under the broader category of Scientific Gnosticism, which is a modern manifestation of Gnosticism.
- Gnosticism is characterized by the belief that the world is fundamentally wrong, humans are trapped in a miserable condition, and through Gnosis, or special knowledge, one can transcend and repair the world.
- The article argues that Gnosticism inverts traditional progress and epistemology, promoting a distorted view that understanding and remaking the world according to one's desires is possible and desirable.
- It critiques modern Scientific Gnosticism, including Marxism and its derivatives, for misusing the prestige of science to promote ideologies that aim to radically alter reality based on theoretical insights.
- The article discusses the failure of these ideologies, including socialism and various forms of identity politics, to deliver on their promises of utopia, attributing their failures to a fundamental misunderstanding of reality and human nature.
- It also touches on the challenge posed by postmodernism to Scientific Gnosticism, arguing that postmodern critiques have been absorbed and repurposed by Scientific Gnostics, leading to a proliferation of identity-based Gnostic ideologies.
- The conclusion is that the resurgence of Gnostic thinking, now in a scientistic and postmodern form, has led to widespread ideological capture and a misguided attempt to remake the world and human beings according to theoretical models, which is ultimately doomed to fail.