---
abstract: Critical Race Theory is currently getting a ton of attention on the national
  and international stage, which is long overdue, but there are also many misconceptions
  about it.
author: James Lindsay
date: '2021-05-24'
link: https://newdiscourses.com/2021/05/five-ugly-truths-about-critical-race-theory/
media_url: ''
title: Five Ugly Truths About Critical Race Theory
---
<https://newdiscourses.com/2021/05/five-ugly-truths-about-critical-race-theory/>

- **Critical Race Theory (CRT) is considered racist** because it emphasizes the social significance of racial categories, advocates for discrimination to "level the playing field," and posits that all white people are either racist or complicit in racism by benefiting from systemic privileges.

- **CRT does not advance the vision and activism of the Civil Rights Movement**. Instead, it questions the foundations of the liberal order, including equality theory and legal reasoning, advocating for revolution over incremental change.

- **CRT posits that all white people are racist** or complicit in racism due to systemic privileges that cannot be voluntarily renounced. It suggests that white people can only strive to be "less white" and condemn "whiteness" as a system.

- **CRT is partially Marxian but not strictly Marxist**. It adapts from neo-Marxism, using race instead of economic class as the line of social stratification. It views "white supremacy" as a superstructure organizing society, similar to how Marxism views capitalism.

- **CRT is not merely an analytical tool for understanding race and racism**; it is a worldview and a movement of activists and scholars. It operates under the assumption that racism is ordinary and systemic, challenging individuals to continually identify, analyze, and challenge racism.