---
abstract: The state of New Hampshire is trying to advance a bill in its state house
  of representatives (HB544) that mirrors the executive order President Trump issued
  "against Critical Race Theory," which is to say against the divisive (and racist/neoracist)
  tenets at the heart of Critical Race Theory and so-called "diversity" training sessions
  based upon it.
author: James Lindsay
date: '2021-03-04'
link: https://newdiscourses.com/2021/03/letter-supporting-bill-ban-critical-race-theory/
media_url: ''
title: A Letter Supporting a Bill to Ban Critical Race Theory
---
<https://newdiscourses.com/2021/03/letter-supporting-bill-ban-critical-race-theory/>

- New Hampshire is considering a bill (HB544) that aims to ban the teaching of divisive tenets associated with Critical Race Theory and similar diversity training sessions.
- The bill is inspired by an executive order issued by President Trump against Critical Race Theory.
- James Lindsay, an expert on Critical Race Theory, testified in support of the bill during a legislative committee meeting on February 18 and has sent a letter urging the committee to endorse the bill.
- HB544 seeks to prohibit state-funded entities from teaching or training in racial and sex stereotyping, scapegoating, and discrimination, as well as labeling the state or institutions as inherently racist or sexist.
- The bill is argued to be necessary due to perceived failures of the Civil Rights Acts and the Fourteenth Amendment to protect against such teachings.
- Lindsay argues that the bill supports freedom of speech and conscience by preventing compulsory adherence to specific ideologies regarding racism and sexism.
- Critical Race Theory is criticized for assuming racism is inherent in all societal interactions and for being divisive, un-American, and resistant to criticism.
- Lindsay urges support for HB544 as a step towards eliminating divisive teachings and upholding fundamental rights, contrasting it with federal moves to embrace Critical Race Theory.