---
abstract: The based aren’t about to live by ridiculous lies because they’ll be too
  busy laughing the bottom out from under them.
author: James Lindsay
date: '2021-05-02'
link: https://newdiscourses.com/2021/05/manifesto-for-the-based/
media_url: ''
title: A Manifesto for the Based
---
<https://newdiscourses.com/2021/05/manifesto-for-the-based/>

- Aleksandr Solzhenitsyn, in his Nobel Lecture, emphasized the importance of not perpetuating lies, a stance described as "based."
- Solzhenitsyn's experiences in Stalin's USSR highlighted the refusal to lie as a key trait for resisting totalitarian regimes.
- The article argues that being "based" involves a refusal to participate in mass delusions or lies, a characteristic crucial for challenging tyranny.
- It suggests that current Western societies are facing similar challenges with widespread acceptance of "transparent lies," posing a threat to democracy and sanity.
- The concept of being "based" is contrasted with being "Woke," with the former associated with truth-telling, humor, and resistance to tyranny, while the latter is criticized for intolerance and promoting falsehoods.
- The origin of "based" is critiqued for its initial association with alt-right ideologies, but the article argues for a broader, more positive interpretation.
- Being "based" is described as being authentic, tolerant (except towards pretense and cruelty), and using humor as a tool against power and absurdity.
- The article concludes that facing current societal absurdities and threats to freedom requires a "based" approach, characterized by humor, truth-telling, and a refusal to be intimidated by lies or tyranny.