---
abstract: According to Critical Race Theory, “racism is ordinary, not aberrational—‘normal
  science,’ the usual way society does business, the common, everyday experience of
  most people of color in this country.” Its advocates call this belief “systemic
  racism.”
author: James Lindsay
date: '2021-08-17'
link: https://newdiscourses.com/2021/08/on-the-absence-of-systemic-racism/
media_url: ''
title: On the Absence of Systemic Racism
---
<https://newdiscourses.com/2021/08/on-the-absence-of-systemic-racism/>

- Critical Race Theory (CRT) posits that racism is ordinary and systemic in society, affecting everyday experiences of people of color.
- CRT is criticized for allegedly finding racism in virtually all aspects of life, including education, government, culture, and policies.
- The article argues that CRT and its proponents selectively apply the concept of systemic racism to support left-leaning agendas, ignoring instances that contradict their narrative.
- Examples cited include discrimination against Asian-Americans in academia, the impact of riots and "defund the police" movements on minority communities, eviction moratoriums affecting small landlords of color, and the potential exclusionary effects of vaccine passports on black and Latino populations.
- The article suggests that the selective outrage and application of systemic racism by CRT advocates reveal a focus on power acquisition rather than genuine concern for racial justice.
- Critics of CRT and the left's use of it argue for a need to challenge the inconsistency and arbitrariness of the systemic racism label as used by its proponents.