---
abstract: What actually triggered the Woke Cultural Revolution in the West?
author: James Lindsay
date: '2021-04-14'
link: https://newdiscourses.com/2021/04/rise-woke-cultural-revolution/
media_url: ''
title: The Rise of the Woke Cultural Revolution
---
<https://newdiscourses.com/2021/04/rise-woke-cultural-revolution/>

- The article discusses the mainstreaming of "Wokeness" from its academic origins to widespread societal acceptance.
- The term "crossing the Tim Pool Gap" is introduced, highlighting the challenge of explaining how "Woke" ideology moved from universities to mainstream culture.
- The article argues that both academia and media played significant roles in spreading Wokeness, with a detailed examination of the influence of Critical Pedagogy in education.
- It outlines a timeline of key events and cultural phenomena that contributed to the rapid spread of Woke ideology, including the presidency of Barack Obama, the Black Lives Matter movement, and the presidency of Donald Trump.
- The article suggests that the mainstreaming of Wokeness was facilitated by a combination of factors, including the internet, social media, and funding from intentional agents promoting the ideology for their agendas.
- It emphasizes the role of education reformers in preparing society for Woke ideology through the promotion of Critical Theory in schools.
- The article critiques the response of both conservatives and liberals to the rise of Wokeness, arguing that many inadvertently helped mainstream the ideology by engaging with it superficially.
- The death of George Floyd is identified as a pivotal moment that triggered a Woke Cultural Revolution, with widespread acceptance and promotion of the ideology.
- The author concludes by warning against placing too much societal trust in the "Respectables" who are unable to withstand criticism and may inadvertently promote harmful ideologies.