---
abstract: If we continue fighting back—for pushing back is no longer enough—intelligently
  and firmly against the ideology of Critical Social Justice and the Woke movement
  it has spawned, we will find ourselves on the road to a post-Woke world, and it
  is not yet clear what that might look like.
author: James Lindsay
date: '2021-03-19'
link: https://newdiscourses.com/2021/03/values-post-woke-world/
media_url: ''
title: The Values of a Post-Woke World
---
<https://newdiscourses.com/2021/03/values-post-woke-world/>

- The article argues against the ideology of Wokeness, describing it as harmful and rooted in totalitarian, racist, and communist thought.
- It suggests that the fight against Wokeness is gaining momentum, with people rejecting its puritanical and totalitarian aspects.
- The author proposes focusing on four cardinal values for a post-Woke world: truth, beauty, liberty, and merit.
- **Truth** is emphasized as the pursuit of objective reality, rejecting subjective "your truth" or "my truth" in favor of evidence, reason, and a process that defers to objective truth.
- **Beauty** is presented as essential for a flourishing society, transcending subjective tastes to embody excellence and inspire aspiration.
- **Liberty** is highlighted as a fundamental condition for a prosperous society, with a focus on individual freedom and responsibility over collectivism.
- **Merit** is advocated as the basis for societal prosperity, emphasizing results, talent, effort, and minimizing corruption.
- The article argues against prioritizing justice as a foundational value, suggesting it should follow from the other four values to avoid injustice.
- It concludes that a post-Woke society should remember and rebuild upon these values to ensure prosperity and flourishing.