---
abstract: There is very little to suggest to me that the Biden administration that
  we have presumably elected to the highest office in the land and as the leadership
  of the free world for at least the next four years is prepared to safeguard its
  people on this issue.
author: James Lindsay
date: '2021-01-03'
link: https://newdiscourses.com/2021/01/woke-make-bidens-moderation-irrelevant/
media_url: ''
title: The Woke Make Biden's "Moderation" Irrelevant
---
<https://newdiscourses.com/2021/01/woke-make-bidens-moderation-irrelevant/>

- The article posits that despite Joe Biden's moderate stance, his administration may not curb the influence of Critical Social Justice (CSJ) and Critical Race Theory (CRT) ideologies.
- It argues that CSJ is designed to infiltrate bureaucratic and administrative systems, suggesting that Biden's appointments and administrative actions will likely support CSJ principles, particularly concerning racial equity.
- The article criticizes Biden for not indicating resistance to what it describes as "bureaucratic totalitarianism" and for appointing individuals who support comprehensive racial justice measures.
- It highlights concerns about the potential for equity-focused policies to lead to racial quotas and redistribution of resources, and it anticipates Biden will reverse Trump's executive order banning certain types of diversity training.
- The piece challenges the Biden administration to justify its support for concepts that the Trump executive order sought to prohibit, questioning how this aligns with the Constitution and civil rights laws.
- It calls for public and repeated questioning of Biden, Harris, and their administration on their commitment to CRT principles and their compatibility with constitutional oaths.
- The article concludes by expressing skepticism about the Biden administration's ability to protect against the perceived threats of CRT and CSJ ideologies, urging accountability from anti-Woke Biden voters.